# Generated by Django 4.2 on 2024-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("season", models.IntegerField(default=0)),
                ("city", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("team1", models.CharField(max_length=200)),
                ("team2", models.CharField(max_length=200)),
                ("toss_winner", models.CharField(max_length=200)),
                ("toss_decision", models.CharField(max_length=200)),
                ("result", models.CharField(max_length=200)),
                ("dl_applied", models.IntegerField(default=0)),
                ("winner", models.CharField(max_length=200)),
                ("win_by_runs", models.IntegerField(default=0)),
                ("win_by_wickets", models.IntegerField(default=0)),
                ("player_of_match", models.CharField(max_length=200)),
                ("venue", models.CharField(max_length=200)),
                ("umpire1", models.CharField(max_length=200)),
                ("umprie2", models.CharField(max_length=200)),
                ("umprie3", models.CharField(max_length=200)),
            ],
        ),
    ]
