# Generated by Django 4.2 on 2024-02-17 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("probs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="umpire1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="umprie2",
        ),
        migrations.RemoveField(
            model_name="match",
            name="umprie3",
        ),
    ]
