# Generated by Django 4.2 on 2024-02-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("probs", "0002_remove_match_umpire1_remove_match_umprie2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.IntegerField()),
                ("batting_team", models.CharField(max_length=200)),
                ("bowling_team", models.CharField(max_length=200)),
                ("over", models.IntegerField()),
                ("ball", models.IntegerField()),
                ("batsman", models.CharField(max_length=200)),
                ("non_striker", models.CharField(max_length=200)),
                ("bowler", models.CharField(max_length=200)),
                ("is_super_over", models.IntegerField()),
                ("wide_runs", models.IntegerField()),
                ("bye_runs", models.IntegerField()),
                ("legbye_runs", models.IntegerField()),
                ("noball_runs", models.IntegerField()),
                ("penalty_runs", models.IntegerField()),
                ("batsman_runs", models.IntegerField()),
                ("extra_runs", models.IntegerField()),
                ("total_runs", models.IntegerField()),
                ("player_dismissed", models.CharField(max_length=200, null=True)),
                ("dismissal_kind", models.CharField(max_length=200, null=True)),
                ("fielder", models.CharField(max_length=200, null=True)),
                (
                    "match_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="probs.match"
                    ),
                ),
            ],
        ),
    ]
